services:
  rbb-website-api:
    build:
      context: /mnt/c/study/RbbSolucoes.Website.Backend.Api
      dockerfile: Dockerfile
    container_name: rbb-website-api
    ports:
      - "5045:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      # Ajuste a connection string conforme seu MongoDB existente
      # - ConnectionStrings__MongoDB=mongodb://root:senha@localhost:27018/?authSource=admin
      - ConnectionStrings__MongoDB=mongodb://root:senha@mongo_local:27017/?authSource=admin
    networks:
      - local-default
      - local-database
      - sherlock-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  local-default:
    external: true
  local-database:
    external: true